<!DOCTYPE html>
<html>
<head>

    <!-- meta -->
    <meta charset="UTF-8" />
    <title>Layout</title>

    <!-- styles -->
    <link type="text/css" rel="stylesheet" href="assets/css/global.css" />

</head>
<body>

<header class="page-header">
    <div class="page-wrap">
        <div class="logo"><img src="assets/img/ACMELogo.png" alt="Acme Logo" width="225" height="70" /></div>
        <div class="page-title">Catalog Of Items</div>
        <nav class="page-nav">
            <ul>
                <li><a href="index.php">Login</a></li>
                <li><a href="catalog.php">Catalog</a></li>
                <li><a href="contact.php">Contact Us</a></li>
            </ul>
        </nav>
        <div class="coyote-logo"><img src="assets/img/Wiley_ACME_LOGO.jpg" alt="Coyote Logo" width="315" height="234" /></div>        
    </div>
</header>


<div class="page-content page-wrap">
<?php echo $content ?>
</div>

<footer class="page-footer">
    <div class="page-wrap"> 
        <div>ACME Corp
            <br />Trademark of the ACME Company and Distribution
            <br />1920-2013. A part of Road-Runner Comgomerate
        </div>
    </div>
</footer>

</body>
</html>
