<form action="" method="post" id="Addressbook">

	<p>Please feel free to enter the name or phone number of the person 
	you are looking for to get the contact information.</p>

	<p>
		<label>First Name <input type="text" name="contact[firstName]"></label>
		<br /><label>Last Name <input type="text" name="contact[lastName]"></label>
		<br /><label>Phone Number <input type="text" name="contact[phone]"></label>
		<br /><label>Address <input type="text" name="contact[address]"></label>
		<br /><label>City <input type="text" name="contact[city]"></label>
		<br /><label>State <input type="text" name="contact[phone]"></label>
		<br /><label>Phone Number <input type="text" name="contact[phone]"></label>
		<br /><label>Phone Number <input type="text" name="contact[phone]"></label>
	</p>
	<table cellspacing="1" cellpadding="0">
        <tbody>
            <td align="right">
                First Name</td>
            <td align="left">
               <input type="text" size="35" name="contact[firstName]" id="fname"> </td>
            <td>
                <input type="submit" name="action" value="Search" id="button_Search"></td>
        </tr>
        <tr>
            <td align="right">
                Last Name</td>
            <td align="left">
                <input type="text" size="35" name="contact[lastName]" id="lname"></td>
            <td>
                <input type="submit" name="action" value="Save" id="Button_save"></td>
        </tr>
        <tr>
            <td align="right">
                Phone Number</td>
            <td align="left">
                <input type="text" size="35" name="contact[phone]" id="phone"></td>
        </tr>
        <tr>
            <td align="right">
                Address</td>
            <td>
                <input type="text" size="35" name="contact[address]" id="address"></td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td align="right">
                City</td>
            <td>
                <input type="text" size="35" name="contact[city]" id="city"></td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td align="right" class="style2">
                State</td>
            <td class="style2">
                <select name="contact[state]">
	                <option value="AL">Alabama</option>
	                <option value="AK">Alaska</option>
	                <option value="AZ">Arizona</option>
	                <option value="AR">Arkansas</option>
	                <option value="CA">California</option>
	                <option value="CO">Colorado</option>
	                <option value="CT">Connecticut</option>
	                <option value="DE">Delaware</option>
	                <option value="DC">District of Columbia</option>
	                <option value="FL">Florida</option>
	                <option value="GA">Georgia</option>
	                <option value="HI">Hawaii</option>
	                <option value="ID">Idaho</option>
	                <option value="IL">Illinois</option>
	                <option value="IN">Indiana</option>
	                <option value="IA">Iowa</option>
	                <option value="KS">Kansas</option>
	                <option value="KY">Kentucky</option>
	                <option value="LA">Louisiana</option>
	                <option value="ME">Maine</option>
	                <option value="MD">Maryland</option>
	                <option value="MA">Massachusetts</option>
	                <option value="MI">Michigan</option>
	                <option value="MN">Minnesota</option>
	                <option value="MS">Mississippi</option>
	                <option value="MO">Missouri</option>
	                <option value="MT">Montana</option>
	                <option value="NE">Nebraska</option>
	                <option value="NV">Nevada</option>
	                <option value="NH">New Hampshire</option>
	                <option value="NJ">New Jersey</option>
	                <option value="NM">New Mexico</option>
	                <option value="NY">New York</option>
	                <option value="NC">North Carolina</option>
	                <option value="ND">North Dakota</option>
	                <option value="OH">Ohio</option>
	                <option value="OK">Oklahoma</option>
	                <option value="OR">Oregon</option>
	                <option value="PA">Pennsylvania</option>
	                <option value="RI">Rhode Island</option>
	                <option value="SC">South Carolina</option>
	                <option value="SD">South Dakota</option>
	                <option value="TN">Tennessee</option>
	                <option value="TX">Texas</option>
	                <option value="UT">Utah</option>
	                <option value="VT">Vermont</option>
	                <option value="VA">Virginia</option>
	                <option value="WA">Washington</option>
	                <option value="WV">West Virginia</option>
	                <option value="WI">Wisconsin</option>
	                <option value="WY">Wyoming</option>
</select>
</td>
            <td class="style2">
                </td>
        </tr>
        <tr>
            <td align="right">
                Zip</td>
            <td>
                <input type="text" size="35" name="contact[zip]" id="zip"></td>
            <td>
                &nbsp;</td>
        </tr>
    </tbody></table>
    </form>