<form action="" method="post" class="contact-form">

	<p>Please feel free to enter the name or phone number of the person 
	you are looking for to get the contact information.</p>

	<div>
		<?php if (!empty($contact['id'])): ?>
		<input type="hidden" name="contact[id]" value="<?php echo $contact['id'] ?>">
		<?php endif ?>
		<label>First Name <input type="text" name="contact[firstName]" value="<?php echo $contact['firstName'] ?>"></label>
		<label>Last Name <input type="text" name="contact[lastName]" value="<?php echo $contact['lastName'] ?>"></label>
		<label>Phone Number <input type="text" name="contact[phone]" value="<?php echo $contact['phone'] ?>"></label>
		<label>Address <input type="text" name="contact[address]" value="<?php echo $contact['address'] ?>"></label>
		<label>City <input type="text" name="contact[city]" value="<?php echo $contact['city'] ?>"></label>
		<label>State 
			<select name="contact[state]">
			<?php

			$states = array(
				'AL' => 'Alabama',
				'AK' => 'Alaska',
				'AZ' => 'Arizona',
				'AR' => 'Arkansas',
				'CA' => 'California',
				'CO' => 'Colorado',
				'CT' => 'Connecticut',
				'DE' => 'Delaware',
				'DC' => 'District of Columbia',
				'FL' => 'Florida',
				'GA' => 'Georgia',
				'HI' => 'Hawaii',
				'ID' => 'Idaho',
				'IL' => 'Illinois',
				'IN' => 'Indiana',
				'IA' => 'Iowa',
				'KS' => 'Kansas',
				'KY' => 'Kentucky',
				'LA' => 'Louisiana',
				'ME' => 'Maine',
				'MD' => 'Maryland',
				'MA' => 'Massachusetts',
				'MI' => 'Michigan',
				'MN' => 'Minnesota',
				'MS' => 'Mississippi',
				'MO' => 'Missouri',
				'MT' => 'Montana',
				'NE' => 'Nebraska',
				'NV' => 'Nevada',
				'NH' => 'New Hampshire',
				'NJ' => 'New Jersey',
				'NM' => 'New Mexico',
				'NY' => 'New York',
				'NC' => 'North Carolina',
				'ND' => 'North Dakota',
				'OH' => 'Ohio',
				'OK' => 'Oklahoma',
				'OR' => 'Oregon',
				'PA' => 'Pennsylvania',
				'RI' => 'Rhode Island',
				'SC' => 'South Carolina',
				'SD' => 'South Dakota',
				'TN' => 'Tennessee',
				'TX' => 'Texas',
				'UT' => 'Utah',
				'VT' => 'Vermont',
				'VA' => 'Virginia',
				'WA' => 'Washington',
				'WV' => 'West Virginia',
				'WI' => 'Wisconsin',
				'WY' => 'Wyoming',
			);
			
			?>
				<option></option>
			<?php foreach ($states as $value => $text): ?>
				<?php $selected = $value == $contact['state'] ?>
				<?php if ($selected): ?>
				<option value="<?php echo $value ?>" selected="selected"><?php echo $text ?></option>
				<?php else: ?>
				<option value="<?php echo $value ?>"><?php echo $text ?></option>
				<?php endif ?>
			<?php endforeach ?>
			</select>
		</label>
		<label>Zip <input type="text" name="contact[zip]" value="<?php echo $contact['zip'] ?>"></label>
	</div>
	
	<div class="actions">
		<button type="submit" name="action" value="search">Search</button>
		<button type="submit" name="action" value="save">Save</button>
	</div>
</form>